// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJWNlq6jSWxx8DyVegKmAFFZhByjZWePc',
    appId: '1:542227336560:web:641a8d81e11cc03b6253b5',
    messagingSenderId: '542227336560',
    projectId: 'mealsapp-95d16',
    authDomain: 'mealsapp-95d16.firebaseapp.com',
    storageBucket: 'mealsapp-95d16.appspot.com',
    measurementId: 'G-QP497KMTZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYR4uhDbR4XtNuvzZzIak4bVpnuZa8S0Y',
    appId: '1:542227336560:android:069b6d3796a2bc156253b5',
    messagingSenderId: '542227336560',
    projectId: 'mealsapp-95d16',
    storageBucket: 'mealsapp-95d16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5s2UPVDo7s2nL4NFy7oAa4U0dxhxJLcE',
    appId: '1:542227336560:ios:131ac27675e8e6db6253b5',
    messagingSenderId: '542227336560',
    projectId: 'mealsapp-95d16',
    storageBucket: 'mealsapp-95d16.appspot.com',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5s2UPVDo7s2nL4NFy7oAa4U0dxhxJLcE',
    appId: '1:542227336560:ios:0c839cf7d11364cb6253b5',
    messagingSenderId: '542227336560',
    projectId: 'mealsapp-95d16',
    storageBucket: 'mealsapp-95d16.appspot.com',
    iosBundleId: 'com.example.recipeApp.RunnerTests',
  );
}
